# Generated by Django 5.0.6 on 2024-07-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('joining_date', models.DateField()),
                ('employee_id', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('company', models.CharField(choices=[('Delta', 'Delta'), ('infotech', 'infotech'), ('TCS', 'TCS')], max_length=20)),
                ('department', models.CharField(choices=[('Web Development', 'Web Development'), ('Marketing', 'Marketing'), ('Backend Development', 'Backend Development'), ('Frontend Development', 'Frontend Development')], max_length=20)),
                ('designation', models.CharField(choices=[('Web Designer', 'Web Designer'), ('Web Developer', 'Web Developer'), ('Android Developer', 'Android Developer'), ('Backend Developer', 'Backend Developer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
